dist: bionic
language: cpp

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get update
        - sudo apt-get purge g++
        - sudo apt-get install clang-10
        - CC=clang-10 && CXX=clang++-10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - xorg-dev 
            - libglu1-mesa-dev
      compiler: clang++-10

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -GNinja .. 
  - cmake --build .